resource "aci_saml_provider" "example" {
  annotation                = "orchestrator:terraform"
  description               = "From Terraform"
  entity_id                 = "entity_id_example" 
  gui_banner_message        = "gui_banner_message_example"
  https_proxy               = "https_proxy_example"
  id_p                      = "adfs"
  key                       = "key_example"
  metadata_url              = "metadata_url_example"
  name                      = "example"
  name_alias                = "saml_provider_alias"
  retries                   = "1"
  sig_alg                   = "SIG_RSA_SHA256"
  timeout                   = "5"
  tp                        = "tp_example"
  want_assertions_encrypted = "yes"
  want_assertions_signed    = "yes"
  want_requests_signed      = "yes"
  want_response_signed      = "yes"
}